admin:
    resource: routes/back/main.yaml
    prefix: /admin

app:
    resource: routes/main.yaml

login:
    path: /login
    defaults: { _controller: App\Controller\SecurityController:login }

logout:
    path: /logout
